config/routes.rb
SmartSpeed::Application.routes.draw do
  root to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  
  resources :guesses do
    collection do
      get 'search'
    end
  end
  

  

end

app/models/guess.rb
class Guess < ActiveRecord::Base
  attr_accessible :address, :latitude, :longitude, :speed_limit, :speed, :street, :city, :state
  attr_accessible :full_address, :notes
 
  geocoded_by :address
  reverse_geocoded_by :latitude, :longitude, :address => :full_address, :state_code => :state
  
  validates :street, length: { maximum: 100 }
  validates :city, presence: true, length: { maximum: 100 }
  validates :state, presence: true, length: { maximum: 2 }
  validates :speed, presence: true, length: { maximum: 3 }
  validates :speed_limit, presence: true, length: { maximum: 3 }
  
  after_validation :geocode, :reverse_geocode
  
  self.per_page = 3
  
  def address
    [street, city, state].compact.join(', ')
  end
    
 # def self.search(search)
#    if search
#      find(:all, :conditions => ['full_address LIKE ?', "%#{search}%"])
#    else
#      find(:all)
#    end
#  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include ApplicationHelper
end

app/controllers/guesses_controller.rb
class GuessesController < ApplicationController
  
  def new
     @guess = Guess.new
  end
  
  def show
    @guess = Guess.find(params[:id])
  end
  
  def index
    @guesses = Guess.paginate(page: params[:page])
  end
  
  def search
    @search = Geocoder.coordinates(params[:search])
    @guesses = Guess.near(@search, 100)
  end
  
  def create
    @guess = Guess.new(params[:guess])
      if @guess.save
        flash[:success] = "Thanks for sharing your speed intuition with other not-slow drivers!"
        redirect_to @guess
      else
        render 'new'
      end   
  end
  
  def destroy
    @guess = Guess.find(params[:id])
    @guess.destroy
    flash[:success] = "Guess destroyed"
    redirect_to guesses_url
  end
  
end
  
  

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Smart Speed"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/guesses/_guess.html.erb
<ul class="list-group">
      <li class="list-group-item">
	    <h4 class="list-group-item-heading">Speed limit</h4>
        <p class="list-group-item-text"><%= @guess.speed_limit %></p>
	 </li>
	
	  <li class="list-group-item">
		<h4 class="list-group-item-heading">Speed to go</h4>
		<p class="list-group-item-text"><%= @guess.speed %></p>
	  </li>
	
	  <li class="list-group-item">
		<h4 class="list-group-item-heading">    Address</h4>
		<p class="list-group-item-text"><%= @guess.full_address %></p>
      </li>

	  <li class="list-group-item">
		<h4 class="list-group-item-heading">   Latitude</h4>
		<p class="list-group-item-text"><%= @guess.latitude %></p>
	  </li>
	
	  <li class="list-group-item">
		<h4 class="list-group-item-heading">  Longitude</h4>
		<p class="list-group-item-text"><%= @guess.longitude %></p>
	  </li>
	
	  <li class="list-group-item">
	    <h4 class="list-group-item-heading">Notes</h4>
		<p class="list-group-item-text"><%= @guess.notes %></p>
	  </li>
              	 <% if @guess.nearbys(50) %>
	  <li class="list-group-item">	
		<h4 class="list-group-heading">Nearby guesses
			<span class="badge"><%= @guess.nearbys.count %></span>
		</h4> 
      
	    <p class="list-group-item-text">
	        <% @guess.nearbys(50).each do |g| %>
				<ul class="nearby-guesses">
				  <li><%= link_to(g.full_address, g) %></li>
				</ul>
		    <% end %>
      
		</p>
	  </li>
	<% end %>
    </ul>

app/views/guesses/_guesses.html.erb
<div class="col-md-12">	
	 <div class="panel panel-info">
	<% @guesses.each do |guess| %>

 
	
	<div class="panel-heading">
	  <h3 class="panel-title">
		<%= link_to("Guess #{guess.id}", guess) %>: <%= guess.speed %>mph in a <%= guess.speed_limit %>mph zone
		</h3>
	</div>
	
	<div class="panel-body">
		<div class="row">
			<div class="col-xs-8">
				<ul class="guesses-stats">
					   <% unless @search.nil? %>
					<li><%= number_with_precision(guess.distance_from(@search), precision: 2) %> miles from search location</li>
					<p></p>
						         <% end %>
					<li>Address: <%= guess.full_address %></li>
						<% if guess.nearbys(50) %>
					<p></p>
					<li>Nearby guesses: 
					  <% guess.nearbys(50).each do |g| %>
					    <%= link_to(g.full_address, g) %>
					  <% end %>
					</li>
					    <% end %>		
			   </ul>  
			</div>
			<div class="col-xs-4">
				<%= image_tag "http://maps.google.com/maps/api/staticmap?size=175x130&sensor=false&zoom=14&markers=#{guess.latitude}%2C#{guess.longitude}" %>
			</div>     
		</div>
	</div>
  	 
  <% end %>
  </div>
</div>

app/views/guesses/index.html.erb
<% provide(:title, 'All') %>
<h2 class="cheader">All guesses</h2>

<div class="row">

<ul class="guesses">
  <%= render :partial => 'guesses', locals: { :guesses => @guesses } %>
	<%= will_paginate @guesses %>
  <%= page_entries_info @guesses, :model => "guesses" %>
</ul>

</div>

app/views/guesses/new.html.erb
<% provide(:title, 'Submit') %>
<div class="row">
	<div class="alert alert-info">Enter any address or intersection along the speed limit zone. </div>
</div>

<div class="row">
  	<div class="col-md-offset-3 col-md-6 col-md-offset-3">
	    <%= form_for(@guess, :html => { class: 'form-horizontal' } ) do |f|%>
	       <%= render 'shared/error_messages', object: f.object %>
			<fieldset>	
				<div class="form-group">
				    <%= f.label :street %>
				    <%= f.text_field :street, :class => "form-control", :placeholder => "Street on which to vroom" %>
				 </div>
				
				<div class="form-group">
				    <%= f.label :city %>
				    <%= f.text_field :city, :class => "form-control", :placeholder => "Schmindianapolis?" %>
				 </div>
				
				<div class="form-group">
				    <%= f.label :state %>
				    <%= f.text_field :state, :class => "form-control", :placeholder => "IN" %>
				 </div>

				<div class="form-group">
				    <%= f.label :speed_limit, :class => "control-label" %>
				    <%= f.text_field :speed_limit, :class => "form-control", :type => "number", :placeholder => 35 %>
				 </div>

				<div class="form-group">
				    <%= f.label :speed, :class => "control-label"	  %>
				    <%= f.text_field :speed, :class => "form-control", :type => "number", :placeholder => 46  %>
				    </div>

				<div class="form-group">
				    <%= f.label :notes, :class => "control-label" %>
				    <%= f.text_area :notes, :class => "input-xlarge", :placeholder => "Watch out for the school zone..." %>
				</div>

				<div class="form-actions">
				<%= f.submit "I solemnly swear that this is good advice", class: "btn btn-lrg btn-primary" %>
				</div>
	       </fieldset>
										      	 <% end %>
       
</div>
</div>

app/views/guesses/search.html.erb
<% provide(:title, 'Search Results') %>
<h2 class="cheader">Search Results</h1>

<div class="row">

<ul class="guesses">
  <%= render :partial => 'guesses', locals: { :guesses => @guesses } %>
</ul>

</div>

app/views/guesses/show.html.erb
<% provide(:title, "Go #{@guess.speed}") %>
<div class="row">
  <aside class="col-sm-4">
    <section>
      <h3>
Keep it around <%= @guess.speed %>
      </h3>

	<%= render 'guess' %>

    </section>
  </aside>
  
  <div class="col-sm-8">
	<div class="container">
      <h3 class="cheader">Map</h3>
      <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@guess.latitude}%2C#{@guess.longitude}" %>
		<div class="timestamp">Created <%= time_ago_in_words(@guess.created_at) %> ago.
	    </div>
	</div>
  </div>

  

</div>

app/views/layouts/_footer.html.erb
<div id="footer">
    <div class="container">
      <p class="muted credit">a <a href="http://twitter.com/Chellberg">Corin Chellberg</a> <a href="http://github.com/chellberg">work in progress</a>.</p>
    </div>
  </div>

app/views/layouts/_header.html.erb
 <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	  <!-- Brand and toggle get grouped for better mobile display -->
	  <div class="navbar-header">
	    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
	      <span class="sr-only">Toggle navigation</span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	    </button>
	     <%= link_to("Smart Speed", root_path, :class => "navbar-brand") %>
	  </div>

	  <!-- Collect the nav links, forms, and other content for toggling -->
	  <div class="collapse navbar-collapse navbar-ex1-collapse">
	    <ul class="nav navbar-nav">
	      <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to("Home", root_path) %></li>
	      <li class="<%= 'active' if current_page?(new_guess_path) %>"><%= link_to("Submit", :controller => :guesses, :action => :new, "data-toggle" => "tab") %></li>
	      <li class="<%= 'active' if current_page?(guesses_path) %>"><%= link_to("All guesses", :controller => :guesses, :action => :index) %></li>
		  <li class="<%= 'active' if current_page?(about_path) %>"><%= link_to("About", :controller => :static_pages, :action => :about, "data-toggle" => "tab") %></li>
		  <li class="<%= 'active' if current_page?(contact_path) %>"><%= link_to("Contact", :controller => :static_pages, :action => :contact, "data-toggle" => "tab" )%></li>
	    </ul>
		 <ul class="nav navbar-nav navbar-right">
		 </ul>
	    <%= render 'layouts/searchform' %>
	   
	  </div><!-- /.navbar-collapse -->
	</nav>

app/views/layouts/_lorem.html.erb
<p> Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima. Eodem modo typi, qui nunc nobis videntur parum clari, fiant sollemnes in futurum. </p>

app/views/layouts/_searchform.html.erb
<%= form_tag(search_guesses_path, method: "get", class: "navbar-form navbar-right", role: "search") do %>
<div class="form-group">
  <%= text_field_tag(:search, nil, placeholder: "Locate guesses near...", class: "form-control", size: 35) %>
</div>
  <%= submit_tag("Search", class: "btn btn-default") %>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<h3 class="cheader">Sidebar</h3>
<ul class="nearby-guesses">
  <li>Latest guesses...</li>
  <li>Coming soon</li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= full_title(yield(:title)) %></title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	  <%= render 'layouts/shim' %>

	  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	</head>

	<body>
	  <div id="wrap">
		
	  <%= render 'layouts/header' %>
	
     <div class="row">	
		<div class="col-md-3 col-sm-3 col-xs-4 sidebar">
		<%= render 'layouts/sidebar' %>
		</div>
		
		<div class="col-md-9 col-sm-9 col-xs-8">
	  <%= yield %>
	    </div>
	
	 </div>
		 <div id ="push"></div>
	   </div>
     </body>

    <%= render 'layouts/footer' %>

</html>

app/views/layouts/application.old.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
 <link href="vendor/assets/stylesheets/bootstrap.css" rel="stylesheet">
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<div id="wrap">
		
  <%= render 'layouts/header' %>
  <%= yield %>
	
	  <div id ="push"></div>
    </div>
</body>

  <%= render 'layouts/footer' %>

</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
   <div id="error_explanation">
     <div class="alert alert-error">
       The form contains <%= pluralize(object.errors.count, "error") %>
     </div>
     <ul>
       <% object.errors.full_messages.each do |msg| %>
       <li>* <%= msg %></li>
       <% end %>
     </ul>
   </div>
   <% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>This is the about page :D</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
  <div class="row">
    <div class="col-md-12">
	
      <div class="jumbotron">
	    <div class="container">
		  <div class="row well well-sm">
			<div class="container">
              <h2 class="cheader">Smart Speed</h2>
                <p class="lead">
		Ever wondered how much to speed on an unfamiliar street? Never wonder again.
		Get crowdsourced local speed intuition with Smart Speed.
                </p>
             </div>
          </div>
	    </div>	
	<%= button_to [:new_guess], { class: "btn btn-primary", method: :get } do %>
				            Submit a speed!
	                            <% end %>	
    </div>
  </div>
</div>